version: "3"

services: 
  node:
    container_name: contact-service
    image: nodeapp-contact
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"
    depends_on: 
      - mongodb
  mongodb:
    container_name: mongodb-contact
    image: mongo
    ports: 
      - "9999:27017"
